export const products = [
  { id: 1, slug: 'bedside-table', name: 'Bedside Table', image: '/images/product-1.jpg', price: 4999, originalPrice: 6999, rating: 4.5, category: 'bedroom', description: 'Elegant wooden bedside table with 2 drawers, perfect for modern bedrooms. Crafted from premium sheesham wood with a smooth natural finish. Features spacious drawers for storing essentials, a sturdy top surface for lamps and books, and tapered legs for a contemporary look. Dimensions: 45cm x 40cm x 55cm.' },
  { id: 2, slug: 'sofa-chair', name: 'Sofa & Chair', image: '/images/product-2.jpg', price: 24999, originalPrice: 34999, rating: 4.8, category: 'living-room', description: 'Luxurious fabric sofa with matching chair, comfortable seating for family gatherings. Upholstered in premium velvet fabric with high-density foam cushioning for superior comfort. The set includes a 3-seater sofa and a complementary accent chair. Features solid wood frame, sinuous spring seat, and removable cushion covers for easy maintenance.' },
  { id: 3, slug: 'tv-unit', name: 'TV Unit', image: '/images/product-3.jpg', price: 12999, originalPrice: 17999, rating: 4.3, category: 'living-room', description: 'Modern TV unit with storage compartments and sleek finish. Features a wall-mounted design with floating shelves and integrated cable management. Made from engineered wood with a high-gloss lacquer finish. Includes open display space, closed cabinets with soft-close hinges, and a dedicated TV mount area suitable for screens up to 55 inches.' },
  { id: 4, slug: 'dining-table-set', name: 'Dining Table Set', image: '/images/product-4.jpg', price: 18999, originalPrice: 24999, rating: 4.6, category: 'dining-room', description: '6-seater dining table set with comfortable chairs, perfect for family meals. The table features a spacious 150cm x 90cm tabletop crafted from solid sheesham wood with a honey finish. Includes 6 matching upholstered dining chairs with solid wood legs. The table has tapered legs and a robust construction designed to last for generations.' },
  { id: 5, slug: 'study-desk', name: 'Study Desk', image: '/images/product-5.jpg', price: 7999, originalPrice: 9999, rating: 4.2, category: 'office', description: 'Compact study desk with drawer storage, ideal for home office. Features a clean, minimalist design with a spacious 110cm x 55cm work surface. Includes a full-width drawer on smooth runners for storing stationery and documents. Constructed from engineered wood with a teak finish and sturdy metal legs. Perfect for work, study, or gaming setups.' },
  { id: 6, slug: 'shoe-rack', name: 'Shoe Rack', image: '/images/product-6.jpg', price: 3999, originalPrice: 5999, rating: 4.4, category: 'entryway', description: 'Wooden shoe rack with multiple shelves, keeps your entryway organized. Features 3 tiers of open shelving and a compact design that fits in any entryway. Made from engineered wood with a walnut finish. Each shelf can hold 3-4 pairs of shoes. Assembly required with simple instructions included.' },
  { id: 7, slug: 'kids-bed', name: 'Kids Bed', image: '/images/product-7.jpg', price: 14999, originalPrice: 19999, rating: 4.7, category: 'kids-room', description: 'Colorful kids bed with safety rails, perfect for childrens bedroom. Designed for children aged 3-8 years, featuring built-in safety rails on both sides to prevent falls. The frame is made from solid pine wood with a vibrant blue finish. Includes a slatted base for proper mattress support and a weight capacity of up to 80kg. Mattress not included.' },
  { id: 8, slug: 'wardrobe', name: 'Wardrobe', image: '/images/product-8.png', price: 22999, originalPrice: 29999, rating: 4.5, category: 'bedroom', description: 'Spacious 3-door wardrobe with mirror and internal shelves. Features a full-height design with 3 hinged doors, a full-length mirror on the center door, and adjustable internal shelving. Made from engineered wood with a frost white finish. Includes a hanging rod, 6 shelves, and 2 drawers. Soft-close hinges prevent slamming. Dimensions: 120cm x 55cm x 200cm.' },
  { id: 9, slug: 'pooja-unit', name: 'Pooja Unit', image: '/images/product-9.png', price: 9999, originalPrice: 13999, rating: 4.6, category: 'pooja-unit', description: 'Traditional pooja unit with compartments for idols and incense. Crafted from solid sheesham wood with intricate carved detailing on the frame. Features multiple tiers and compartments for placing idols, a dedicated space for a priest bell, and storage for incense sticks and camphor. The warm honey finish complements traditional and modern interiors alike.' },
  { id: 10, slug: 'modular-kitchen', name: 'Modular Kitchen', image: '/images/product-10.png', price: 59999, originalPrice: 79999, rating: 4.8, category: 'kitchen', description: 'L-shaped modular kitchen with premium finish and ample storage. This comprehensive kitchen solution includes wall-mounted and base cabinets with soft-close mechanisms. Features a stainless steel sink, granite countertop, and modular hardware throughout. The high-gloss acrylic finish is easy to clean and resistant to moisture. Professional installation included. Custom configurations available.' },
  { id: 11, slug: 'crockery-unit', name: 'Crockery Unit', image: '/images/product-11.png', price: 8999, originalPrice: 11999, rating: 4.3, category: 'dining-room', description: 'Elegant crockery unit with glass doors to display your collection. Features a 4-tier design with open shelving on one side and glass-fronted display cabinets on the other. Made from engineered wood with a rich walnut finish. The glass doors have soft-close mechanisms and LED-ready interiors for showcasing your finest dinnerware and glassware.' },
  { id: 12, slug: 'almirah', name: 'Almirah', image: '/images/product.jpg', price: 15999, originalPrice: 21999, rating: 4.4, category: 'bedroom', description: 'Sturdy almirah with locker compartment and adjustable shelves. This 2-door wardrobe features a compact yet spacious design ideal for smaller bedrooms. Includes a built-in locker compartment with a lock for valuables, an adjustable hanging rod, and 4 adjustable shelves. The engineered wood construction with a matte grey finish suits contemporary bedroom decors.' },
];
